/*
 *  File: idt.h
 *  Author: Vincent Cupo
 *  
 * 	THIS FILE IS NOT TO BE VIEWED BY THE GENERAL PUBLIC WITHOUT 
 * 	WRITTEN CONSENT OF PSIONIX SOFTWORKS LLC.
 * 
 *  PROPERTY OF PSIONIX SOFTWORKS LLC.
 *  Copyright (c) 2018-2020, Psionix Softworks LLC.
 *
 */

#ifndef ADAMANTINE_INTERRUPT_DESCRIPTOR_TABLE
#define ADAMANTINE_INTERRUPT_DESCRIPTOR_TABLE

// Includes go here:
#include "../aos-defs.h"
#include "../types.h"

#ifndef INTERRUPT_DESCRIPTOR
#define INTERRUPT_DESCRIPTOR
#endif

struct IDT_Entry 
{
	UWORD 				BaseLo;
	UWORD 				Selector;
	UBYTE 				AlwaysZero;
	UBYTE 				Flags;
	UWORD 				BaseHi;
} PACKED;
typedef struct IDT_Entry IDT_Entry_t;

struct PIDT 
{
	UWORD 				Limit;
	UDWORD 				Base;
} PACKED;
typedef struct PIDT PIDT_t;

EXTERN	VOID (ISR_0(VOID));
EXTERN	VOID (ISR_1(VOID));
EXTERN	VOID (ISR_2(VOID));
EXTERN	VOID (ISR_3(VOID));
EXTERN	VOID (ISR_4(VOID));
EXTERN	VOID (ISR_5(VOID));
EXTERN	VOID (ISR_6(VOID));
EXTERN	VOID (ISR_7(VOID));
EXTERN	VOID (ISR_8(VOID));
EXTERN	VOID (ISR_9(VOID));
EXTERN	VOID (ISR_10(VOID));
EXTERN	VOID (ISR_11(VOID));
EXTERN	VOID (ISR_12(VOID));
EXTERN	VOID (ISR_13(VOID));
EXTERN	VOID (ISR_14(VOID));
EXTERN	VOID (ISR_15(VOID));
EXTERN	VOID (ISR_16(VOID));
EXTERN	VOID (ISR_17(VOID));
EXTERN	VOID (ISR_18(VOID));
EXTERN	VOID (ISR_19(VOID));
EXTERN	VOID (ISR_20(VOID));
EXTERN	VOID (ISR_21(VOID));
EXTERN	VOID (ISR_22(VOID));
EXTERN	VOID (ISR_23(VOID));
EXTERN	VOID (ISR_24(VOID));
EXTERN	VOID (ISR_25(VOID));
EXTERN	VOID (ISR_26(VOID));
EXTERN	VOID (ISR_27(VOID));
EXTERN	VOID (ISR_28(VOID));
EXTERN	VOID (ISR_29(VOID));
EXTERN	VOID (ISR_30(VOID));
EXTERN	VOID (ISR_31(VOID));

EXTERN	VOID (IRQ_0(VOID));
EXTERN	VOID (IRQ_1(VOID));
EXTERN	VOID (IRQ_2(VOID));
EXTERN	VOID (IRQ_3(VOID));
EXTERN	VOID (IRQ_4(VOID));
EXTERN	VOID (IRQ_5(VOID));
EXTERN	VOID (IRQ_6(VOID));
EXTERN	VOID (IRQ_7(VOID));
EXTERN	VOID (IRQ_8(VOID));
EXTERN	VOID (IRQ_9(VOID));
EXTERN	VOID (IRQ_10(VOID));
EXTERN	VOID (IRQ_11(VOID));
EXTERN	VOID (IRQ_12(VOID));
EXTERN	VOID (IRQ_13(VOID));
EXTERN	VOID (IRQ_14(VOID));
EXTERN	VOID (IRQ_15(VOID));

EXTERN 	VOID (IDT_Init(VOID));
EXTERN 	VOID (IDT_Free(VOID));

#endif	// !ADAMANTINE_INTERRUPT_DESCRIPTOR_TABLE
