#ifndef _ADAMANTINE_VERSION_H
#define _ADAMANTINE_VERSION_H

#define OS_NAME             "AdamantineOS"
#define OS_VERSION_STRING   "0.5.20.2a"
#define OS_VERSION_MAJOR    0
#define OS_VERSION_MINOR    5
#define OS_VERSION_BUILD    20
#define OS_VERSION_RELEASE  2

#define OS_VERSION_NUMBER   (OS_VERSION_MAJOR * OS_VERSION_MINOR + OS_VERSION_BUILD * OS_VERSION_RELEASE)
#define AOSAPI_VER  (OS_VERSION_NUMBER >> 2)
#endif
