#ifndef _AOS_VERSION_H
#define _AOS_VERSION_H

#define KERNEL_NAME             "adamantine"
#define KERNEL_VERSION_STRING   "0.5.20.2a"
#define KERNEL_VERSION_MAJOR    0
#define KERNEL_VERSION_MINOR    5
#define KERNEL_VERSION_BUILD    20
#define KERNEL_VERSION_RELEASE  2

#define KERNEL_VERSION_NUMBER   (KERNEL_VERSION_MAJOR * KERNEL_VERSION_MINOR + KERNEL_VERSION_BUILD * KERNEL_VERSION_RELEASE)
#define AOSAPI_VER  (KERNEL_VERSION_NUMBER >> 2)
#endif  // !_AOS_VERSION_H
